language: python
python:
  - 2.7

service:
  - docker

install:
  - docker build -t shoutcast .
  - docker run -d -p 127.0.0.1:10128:10128 -p 127.0.0.1:10129:10129 --name shoutcast shoutcast

script:
  - docker ps | grep -q shoutcast
